db:
  username: cassandra
  password: cassandra
  keyspace: public
  host: cassandra
server:
  address: 0.0.0.0:8080
smtp:
  host: smtp.gmail.com
  port: 587
  from: ***REMOVED***
  password: ***REMOVED***
