db:
  username: cassandra
  password: cassandra
  keyspace: public
  host: localhost
server:
  address: 0.0.0.0:8080
smtp:
  address: smtp.gmail.com:587
  from: ***REMOVED***
  password: ***REMOVED***
