db:
  username: cassandra
  password: cassandra
  keyspace: public
  host: localhost
server:
  address: 0.0.0.0:8080
smtp:
  address: smtp.gmail.com:587
  from: reqgo1239@gmail.com
  password: GoAlpine@@@!!123
